EasyShape/Controllers/ShapeController.cs
using CommandProcessor;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JeyLabs.Controllers
{
    public class ShapeController : Controller
    {

        private ICommandProcessor commandProcessor;

        public ShapeController(ICommandProcessor commandProcessor)
        {
            this.commandProcessor = commandProcessor;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View("CreateShape");
        }

        /// <summary>
        /// This is called by the Ajax call from the clint side with a command
        /// </summary>
        /// <param name="drawCommand"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult Create(string drawCommand)
        {   
            //convert the dynamic object to json string --> this will be helpfull to flatten the dynamic object
            return Json(new { Shape = JsonConvert.SerializeObject(commandProcessor.ProcessCommand(drawCommand)) });
        }
    }
}

EasyShape/Views/Shape/About.cshtml
@{
    ViewBag.Title = "About";
}

<div class="jumbotron">
    <p>This is an ASP.NET MVC web application which has been built as an assignment - Easy Shape.</p>
</div>
<div class="jumbotron">
    <h1>Easy Shapes</h1>
    <p>The most important attribute of the human being is the <b>Curiosity</b>. It has helped the entire human nature to become the most powerful living being in the world. In the recent past, the man has made most of his tasks automatic using various available technologies. While most of the people overlook the future with different innovations, there are a lot of existing manual activites that can be automated to make the man's life a lot easier. Natural Language Processing has been a key factor of the Human Computer Interactions. Someone should find the small holes there and provide some smart solutions to make a better life for the people. Making the computer interactions easier, thus saving the valuable time.</p>
    <p>We have named this project <b>Easy Shapes</b> because using simple commands, we can create shapes using this.</p>
</div>

EasyShape/Views/Shape/CreateShape.cshtml
@{
    ViewBag.Title = "Create Shapes";
}

@Styles.Render("~/Content/create-shapes")
<div class="jumbotron">
    Draw Shapes
</div>

<div class="row input-area">
    <div class="form-group">
        Please enter what you want to draw in the following format.<br />
        "<i>Draw a(n) <b>shape</b> with a(n) <b>measurement</b> of <b>amount</b> (and a(n) <b>measurement</b> of <b>amount</b></i>" <br />
        All the measurements are in pixels for 2D shapes. 3D shapes measurements can be any unit(m,cm etc)<br />
        Ex:
        <ul>
            <li><b>Draw an octagon with a side length of 200</b></li>
            <li><b>Draw an isosceles triangle with a height of 200 and a width of 100</b></li>
        </ul>
        <textarea class="form-control" id="simpleCommand" name="simpleCommand" rows="5" onclick="CreateShapes.ResetMessage();"></textarea>
        <div id="message" class="message-area" hidden></div>
    </div>

    <button id="submit" class="btn btn-primary" onclick="CreateShapes.SendCommand();">Draw</button>
</div>
@Scripts.Render("~/bundles/3dshapes")
<canvas id="shape" class="canvas" resize> Your browser does not support the HTML 5 Canvas. </canvas>

@Scripts.Render("~/bundles/2dshapes")
@Scripts.Render("~/bundles/shapes")

EasyShape/Views/Shape/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Easy Shapes</h1>
    <p>The most important attribute of the human being is the <b>Curiosity</b>. It has helped the entire human nature to become the most powerful living being in the world. In the recent past, the man has made most of his tasks automatic using various available technologies. While most of the people overlook the future with different innovations, there are a lot of existing manual activites that can be automated to make the man's life a lot easier. Natural Language Processing has been a key factor of the Human Computer Interactions. Someone should find the small holes there and provide some smart solutions to make a better life for the people. Making the computer interactions easier, thus saving the valuable time.</p>
    <p>We have named this project <b>Easy Shapes</b> because using simple commands, we can create shapes using this.</p>
</div>

<div class="row">
    <div class="col-md-4">
        @Html.ActionLink("Create Shapes", "Create", "Shape", null, new { @class = "btn btn-primary" })
    </div>
</div>

EasyShape/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Easy Shapes</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="loading" hidden>Loading&#8230;</div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Easy Shape", "Index", "Shape", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Shape")</li>
                    <li>@Html.ActionLink("About", "About", "Shape")</li>      
                    <li>@Html.ActionLink("Create Shapes", "Create", "Shape")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Easy Shape</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/common-support")
    @RenderSection("scripts", required: false)
</body>
</html>